export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';
export const DELETE_PRODUCTS_SUCCESS = 'DELETE_PRODUCTS_SUCCESS';
export const DELETE_PRODUCTS_FAILED = 'DELETE_PRODUCTS_FAILED';
export const RESET_DELETE_PRODUCTS = 'RESET_DELETE_PRODUCTS';
