export const DELETE_SUPPLIER = 'DELETE_SUPPLIER';
export const DELETE_SUPPLIER_SUCCESS = 'DELETE_SUPPLIER_SUCCESS';
export const DELETE_SUPPLIER_FAILED = 'DELETE_SUPPLIER_FAILED';
export const RESET_DELETE_SUPPLIER = 'RESET_DELETE_SUPPLIER';
