export const MINI_SEARCH_PRODUCTS = 'MINI_SEARCH_PRODUCTS';
export const MINI_SEARCH_PRODUCTS_SUCCESS = 'MINI_SEARCH_PRODUCTS_SUCCESS';
export const MINI_SEARCH_PRODUCTS_FAILED = 'MINI_SEARCH_PRODUCTS_FAILED';
export const RESET_MINI_SEARCH_PRODUCTS = 'RESET_MINI_SEARCH_PRODUCTS';
