export const UPDATE_SUPPLIER = 'UPDATE_SUPPLIER';
export const UPDATE_SUPPLIER_SUCCESS = 'UPDATE_SUPPLIER_SUCCESS';
export const UPDATE_SUPPLIER_FAILED = 'UPDATE_SUPPLIER_FAILED';
export const RESET_UPDATE_SUPPLIER = 'RESET_UPDATE_SUPPLIER';
