export const GET_ALL_KEYSEARCH = 'GET_ALL_KEYSEARCH';
export const GET_ALL_KEYSEARCH_SUCCESS = 'GET_ALL_KEYSEARCH_SUCCESS';
export const GET_ALL_KEYSEARCH_FAILED = 'GET_ALL_KEYSEARCH_FAILED';
export const RESET_GET_ALL_KEYSEARCH = 'RESET_GET_ALL_KEYSEARCH';
