export const SUGGEST_MINI_SEARCH_PRODUCTS = 'SUGGEST_MINI_SEARCH_PRODUCTS';
export const SUGGEST_MINI_SEARCH_PRODUCTS_SUCCESS = 'SUGGEST_MINI_SEARCH_PRODUCTS_SUCCESS';
export const SUGGEST_MINI_SEARCH_PRODUCTS_FAILED = 'SUGGEST_MINI_SEARCH_PRODUCTS_FAILED';
export const RESET_SUGGEST_MINI_SEARCH_PRODUCTS = 'RESET_SUGGEST_MINI_SEARCH_PRODUCTS';
