export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const UPDATE_PRODUCTS_SUCCESS = 'UPDATE_PRODUCTS_SUCCESS';
export const UPDATE_PRODUCTS_FAILED = 'UPDATE_PRODUCTS_FAILED';
export const RESET_UPDATE_PRODUCTS = 'RESET_UPDATE_PRODUCTS';
