export const GET_PRODUCT_IMAGE = 'GET_PRODUCT_IMAGE';
export const GET_PRODUCT_IMAGE_SUCCESS = 'GET_PRODUCT_IMAGE_SUCCESS';
export const GET_PRODUCT_IMAGE_FAILED = 'GET_PRODUCT_IMAGE_FAILED';
export const RESET_GET_PRODUCT_IMAGE = 'RESET_GET_PRODUCT_IMAGE';

export const GET_PRODUCT_SMALL_IMAGE = 'GET_PRODUCT_SMALL_IMAGE';
export const GET_PRODUCT_SMALL_IMAGE_SUCCESS = 'GET_PRODUCT_SMALL_IMAGE_SUCCESS';
export const GET_PRODUCT_SMALL_IMAGE_FAILED = 'GET_PRODUCT_SMALL_IMAGE_FAILED';
export const RESET_GET_PRODUCT_SMALL_IMAGE = 'RESET_GET_PRODUCT_SMALL_IMAGE';
