export const LARGE_SEARCH_PRODUCTS = 'LARGE_SEARCH_PRODUCTS';
export const LARGE_SEARCH_PRODUCTS_SUCCESS = 'LARGE_SEARCH_PRODUCTS_SUCCESS';
export const LARGE_SEARCH_PRODUCTS_FAILED = 'LARGE_SEARCH_PRODUCTS_FAILED';
export const RESET_LARGE_SEARCH_PRODUCTS = 'RESET_LARGE_SEARCH_PRODUCTS';
