export const CREATE_PRODUCTS = 'CREATE_PRODUCTS';
export const CREATE_PRODUCTS_SUCCESS = 'CREATE_PRODUCTS_SUCCESS';
export const CREATE_PRODUCTS_FAILED = 'CREATE_PRODUCTS_FAILED';
export const RESET_CREATE_PRODUCTS = 'RESET_CREATE_PRODUCTS';
