export const CREATE_SUPPLIER = 'CREATE_SUPPLIER';
export const CREATE_SUPPLIER_SUCCESS = 'CREATE_SUPPLIER_SUCCESS';
export const CREATE_SUPPLIER_FAILED = 'CREATE_SUPPLIER_FAILED';
export const RESET_CREATE_SUPPLIER = 'RESET_CREATE_SUPPLIER';
